/* ====================================================================
 * Copyright (c) 2001-2005 The OpenSSL Project.  All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 *
 * 1. Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer. 
 *
 * 2. Redistributions in binary form must reproduce the above copyright
 *    notice, this list of conditions and the following disclaimer in
 *    the documentation and/or other materials provided with the
 *    distribution.
 *
 * 3. All advertising materials mentioning features or use of this
 *    software must display the following acknowledgment:
 *    "This product includes software developed by the OpenSSL Project
 *    for use in the OpenSSL Toolkit. (http://www.openssl.org/)"
 *
 * 4. The names "OpenSSL Toolkit" and "OpenSSL Project" must not be used to
 *    endorse or promote products derived from this software without
 *    prior written permission. For written permission, please contact
 *    openssl-core@openssl.org.
 *
 * 5. Products derived from this software may not be called "OpenSSL"
 *    nor may "OpenSSL" appear in their names without prior written
 *    permission of the OpenSSL Project.
 *
 * 6. Redistributions of any form whatsoever must retain the following
 *    acknowledgment:
 *    "This product includes software developed by the OpenSSL Project
 *    for use in the OpenSSL Toolkit (http://www.openssl.org/)"
 *
 * THIS SOFTWARE IS PROVIDED BY THE OpenSSL PROJECT ``AS IS'' AND ANY
 * EXPRESSED OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
 * IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR
 * PURPOSE ARE DISCLAIMED.  IN NO EVENT SHALL THE OpenSSL PROJECT OR
 * ITS CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
 * SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT
 * NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
 * LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
 * HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT,
 * STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
 * ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED
 * OF THE POSSIBILITY OF SUCH DAMAGE.
 * ====================================================================
 *
 * This product includes cryptographic software written by Eric Young
 * (eay@cryptsoft.com).  This product includes software written by Tim
 * Hudson (tjh@cryptsoft.com).
 *
 */

#ifndef HEADER_DSTU_ERR_H
#define HEADER_DSTU_ERR_H

#include <openssl/err.h>

#ifdef  __cplusplus
extern "C" {
#endif

/* BEGIN ERROR CODES */
/* The following lines are auto generated by the script mkerr.pl. Any changes
 * made after this point may be overwritten when the script is next run.
 */
void ERR_load_DSTU_strings(void);
void ERR_unload_DSTU_strings(void);
void ERR_DSTU_error(int function, int reason, char *file, int line);
#define DSTUerr(f,r) ERR_DSTU_error((f),(r),__FILE__,__LINE__)

/* Error codes for the DSTU functions. */

/* Function codes. */
#define DSTU_F_BIND_DSTU				 100
#define DSTU_F_DSTU_ASN1_PARAM_COPY			 102
#define DSTU_F_DSTU_ASN1_PARAM_DECODE			 101
#define DSTU_F_DSTU_ASN1_PARAM_ENCODE			 103
#define DSTU_F_DSTU_ASN1_PARAM_PRINT			 104
#define DSTU_F_DSTU_ASN1_PRIV_DECODE			 105
#define DSTU_F_DSTU_ASN1_PRIV_ENCODE			 106
#define DSTU_F_DSTU_ASN1_PUB_DECODE			 107
#define DSTU_F_DSTU_ASN1_PUB_ENCODE			 108
#define DSTU_F_DSTU_DO_SIGN				 109
#define DSTU_F_DSTU_DO_VERIFY				 110
#define DSTU_F_DSTU_PKEY_INIT_BE			 111
#define DSTU_F_DSTU_PKEY_INIT_LE			 112
#define DSTU_F_DSTU_PKEY_KEYGEN				 113
#define DSTU_F_DSTU_PKEY_SIGN				 114
#define DSTU_F_DSTU_PKEY_VERIFY				 115

/* Reason codes. */
#define DSTU_R_AMETH_INIT_FAILED			 100
#define DSTU_R_ASN1_PARAMETER_ENCODE_FAILED		 103
#define DSTU_R_INCORRECT_FIELD_TYPE			 107
#define DSTU_R_INVALID_ASN1_PARAMETERS			 102
#define DSTU_R_NOT_DSTU_KEY				 104
#define DSTU_R_PMETH_INIT_FAILED			 101
#define DSTU_R_POINT_COMPRESS_FAILED			 105
#define DSTU_R_POINT_UNCOMPRESS_FAILED			 106

#ifdef  __cplusplus
}
#endif
#endif
